version: '3.8'

services:
  n8n:
    image: n8nio/n8n:1.106.3
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=EntreGA2025!
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_ENCRYPTION_KEY=EntreGA2025!EncryptionKey32Chars
      - N8N_DATABASE_TYPE=sqlite
      - N8N_DATABASE_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network

volumes:
  n8n_data:

networks:
  n8n_network:
    driver: bridge
