"""add_whatsapp_integration_lifecycle_fields

Revision ID: 7313ca3bd0fe
Revises: 46e48f7ce8a6
Create Date: 2026-04-10 12:26:03.749838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7313ca3bd0fe"
down_revision: Union[str, None] = "46e48f7ce8a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenant_whatsapp_integrations",
        sa.Column("last_validated_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "tenant_whatsapp_integrations",
        sa.Column("disconnected_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "tenant_whatsapp_integrations",
        sa.Column("metadata_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "tenant_whatsapp_integrations",
        sa.Column(
            "onboarding_nonce", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "tenant_whatsapp_integrations",
        sa.Column("onboarding_nonce_expires_at", sa.DateTime(), nullable=True),
    )
    op.alter_column(
        "tenant_whatsapp_integrations",
        "connected_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenants", "billing_status", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tenants", "billing_status", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "tenant_whatsapp_integrations",
        "connected_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("tenant_whatsapp_integrations", "onboarding_nonce_expires_at")
    op.drop_column("tenant_whatsapp_integrations", "onboarding_nonce")
    op.drop_column("tenant_whatsapp_integrations", "metadata_json")
    op.drop_column("tenant_whatsapp_integrations", "disconnected_at")
    op.drop_column("tenant_whatsapp_integrations", "last_validated_at")
    # ### end Alembic commands ###
