"""phase5_consistency

Revision ID: 805150294c2d
Revises: e4f5a6b7
Create Date: 2026-04-11 12:57:49.450720

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "805150294c2d"
down_revision: Union[str, None] = "e4f5a6b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metric_reconciliations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("metric_date", sa.DateTime(), nullable=False),
        sa.Column(
            "snapshot_values", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("truth_values", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("drift_detected", sa.Boolean(), nullable=False),
        sa.Column("drift_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reconciled_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metric_reconciliations_drift_detected"),
        "metric_reconciliations",
        ["drift_detected"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_reconciliations_metric_date"),
        "metric_reconciliations",
        ["metric_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_reconciliations_tenant_id"),
        "metric_reconciliations",
        ["tenant_id"],
        unique=False,
    )
    op.drop_index(
        op.f("idx_customer_balances_tenant_balance"), table_name="customer_balances"
    )
    op.drop_index(
        op.f("idx_inventory_movements_tenant_type_created"),
        table_name="inventory_movements",
    )
    op.add_column(
        "metric_snapshots",
        sa.Column("last_reconciled_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "metric_snapshots",
        sa.Column("update_counter", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "metric_snapshots",
        sa.Column("last_error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_constraint(
        op.f("uq_metric_snapshot_tenant_name_period"),
        "metric_snapshots",
        type_="unique",
    )
    op.create_index(
        op.f("ix_metric_snapshots_period_end"),
        "metric_snapshots",
        ["period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_snapshots_period_start"),
        "metric_snapshots",
        ["period_start"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_metric_snapshot",
        "metric_snapshots",
        ["tenant_id", "metric_name", "period_start"],
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.drop_index(op.f("idx_payments_tenant_created"), table_name="payments")
    op.drop_index(
        op.f("idx_stock_balances_tenant_quantity"), table_name="stock_balances"
    )
    op.alter_column(
        "tenant_whatsapp_integrations",
        "token_expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_whatsapp_integrations",
        "display_phone_number",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_whatsapp_integrations",
        "setup_completed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_constraint(
        op.f("uq_whatsapp_phone_number_id"),
        "tenant_whatsapp_integrations",
        type_="unique",
    )
    op.create_index(
        op.f("ix_tenant_whatsapp_integrations_last_error_code"),
        "tenant_whatsapp_integrations",
        ["last_error_code"],
        unique=False,
    )
    op.alter_column(
        "whatsapp_messages",
        "last_error",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_whatsapp_messages_status"), table_name="whatsapp_messages")
    op.drop_index(
        op.f("idx_whatsapp_messages_tenant_status"), table_name="whatsapp_messages"
    )
    op.drop_index(
        op.f("ix_whatsapp_messages_from_number"), table_name="whatsapp_messages"
    )
    op.create_index(
        op.f("ix_whatsapp_messages_last_error_code"),
        "whatsapp_messages",
        ["last_error_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_whatsapp_messages_phone_number_id"),
        "whatsapp_messages",
        ["phone_number_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_whatsapp_messages_processing_status"),
        "whatsapp_messages",
        ["processing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_whatsapp_messages_sender_wa_id"),
        "whatsapp_messages",
        ["sender_wa_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_whatsapp_messages_tenant_id"),
        "whatsapp_messages",
        ["tenant_id"],
        unique=False,
    )
    op.drop_column("whatsapp_messages", "from_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "whatsapp_messages",
        sa.Column("from_number", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(
        op.f("ix_whatsapp_messages_tenant_id"), table_name="whatsapp_messages"
    )
    op.drop_index(
        op.f("ix_whatsapp_messages_sender_wa_id"), table_name="whatsapp_messages"
    )
    op.drop_index(
        op.f("ix_whatsapp_messages_processing_status"), table_name="whatsapp_messages"
    )
    op.drop_index(
        op.f("ix_whatsapp_messages_phone_number_id"), table_name="whatsapp_messages"
    )
    op.drop_index(
        op.f("ix_whatsapp_messages_last_error_code"), table_name="whatsapp_messages"
    )
    op.create_index(
        op.f("ix_whatsapp_messages_from_number"),
        "whatsapp_messages",
        ["from_number"],
        unique=False,
    )
    op.create_index(
        op.f("idx_whatsapp_messages_tenant_status"),
        "whatsapp_messages",
        ["tenant_id", "processing_status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_whatsapp_messages_status"),
        "whatsapp_messages",
        ["processing_status"],
        unique=False,
    )
    op.alter_column(
        "whatsapp_messages",
        "last_error",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_tenant_whatsapp_integrations_last_error_code"),
        table_name="tenant_whatsapp_integrations",
    )
    op.create_unique_constraint(
        op.f("uq_whatsapp_phone_number_id"),
        "tenant_whatsapp_integrations",
        ["phone_number_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "tenant_whatsapp_integrations",
        "setup_completed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "tenant_whatsapp_integrations",
        "display_phone_number",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_whatsapp_integrations",
        "token_expires_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.create_index(
        op.f("idx_stock_balances_tenant_quantity"),
        "stock_balances",
        ["tenant_id", "quantity"],
        unique=False,
    )
    op.create_index(
        op.f("idx_payments_tenant_created"),
        "payments",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_constraint("uq_metric_snapshot", "metric_snapshots", type_="unique")
    op.drop_index(
        op.f("ix_metric_snapshots_period_start"), table_name="metric_snapshots"
    )
    op.drop_index(op.f("ix_metric_snapshots_period_end"), table_name="metric_snapshots")
    op.create_unique_constraint(
        op.f("uq_metric_snapshot_tenant_name_period"),
        "metric_snapshots",
        ["tenant_id", "metric_name", "period_start"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("metric_snapshots", "last_error_code")
    op.drop_column("metric_snapshots", "update_counter")
    op.drop_column("metric_snapshots", "last_reconciled_at")
    op.create_index(
        op.f("idx_inventory_movements_tenant_type_created"),
        "inventory_movements",
        ["tenant_id", "type", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_customer_balances_tenant_balance"),
        "customer_balances",
        ["tenant_id", "balance"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_metric_reconciliations_tenant_id"), table_name="metric_reconciliations"
    )
    op.drop_index(
        op.f("ix_metric_reconciliations_metric_date"),
        table_name="metric_reconciliations",
    )
    op.drop_index(
        op.f("ix_metric_reconciliations_drift_detected"),
        table_name="metric_reconciliations",
    )
    op.drop_table("metric_reconciliations")
    # ### end Alembic commands ###
