"""add business_metric_events table

Revision ID: 909b7521037d
Revises: f7d2a5e4b9c1
Create Date: 2026-04-09 22:09:22.646177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '909b7521037d'
down_revision: Union[str, None] = 'f7d2a5e4b9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_before', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_after', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_index(op.f('ix_audit_logs_performed_by'), 'audit_logs', ['performed_by'], unique=False)
    op.create_table('platform_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recommended_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('snapshot_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_alerts_created_at'), 'platform_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_platform_alerts_is_active'), 'platform_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_platform_alerts_severity'), 'platform_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_platform_alerts_tenant_id'), 'platform_alerts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_platform_alerts_type'), 'platform_alerts', ['type'], unique=False)
    op.create_table('business_metric_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_metric_events_created_at'), 'business_metric_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_business_metric_events_event_type'), 'business_metric_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_business_metric_events_tenant_id'), 'business_metric_events', ['tenant_id'], unique=False)
    op.alter_column('inventory_movements', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('products', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('system_settings', 'key',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('system_settings', 'value',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('system_settings', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_whatsapp_integrations', 'provider',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'meta'::text"))
    op.alter_column('tenant_whatsapp_integrations', 'business_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tenant_whatsapp_integrations', 'waba_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tenant_whatsapp_integrations', 'phone_number_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tenant_whatsapp_integrations', 'access_token_encrypted',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('tenant_whatsapp_integrations', 'status',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('tenant_whatsapp_integrations', 'connected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_whatsapp_integrations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_whatsapp_phone_id'), table_name='tenant_whatsapp_integrations')
    op.drop_index(op.f('idx_whatsapp_tenant_id'), table_name='tenant_whatsapp_integrations')
    op.drop_index(op.f('idx_whatsapp_waba_id'), table_name='tenant_whatsapp_integrations')
    op.drop_constraint(op.f('tenant_whatsapp_integrations_phone_number_id_key'), 'tenant_whatsapp_integrations', type_='unique')
    op.create_index(op.f('ix_tenant_whatsapp_integrations_phone_number_id'), 'tenant_whatsapp_integrations', ['phone_number_id'], unique=True)
    op.create_index(op.f('ix_tenant_whatsapp_integrations_tenant_id'), 'tenant_whatsapp_integrations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_whatsapp_integrations_waba_id'), 'tenant_whatsapp_integrations', ['waba_id'], unique=False)
    op.drop_constraint(op.f('tenant_whatsapp_integrations_tenant_id_fkey'), 'tenant_whatsapp_integrations', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_whatsapp_integrations', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_whatsapp_integrations', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_whatsapp_integrations_tenant_id_fkey'), 'tenant_whatsapp_integrations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tenant_whatsapp_integrations_waba_id'), table_name='tenant_whatsapp_integrations')
    op.drop_index(op.f('ix_tenant_whatsapp_integrations_tenant_id'), table_name='tenant_whatsapp_integrations')
    op.drop_index(op.f('ix_tenant_whatsapp_integrations_phone_number_id'), table_name='tenant_whatsapp_integrations')
    op.create_unique_constraint(op.f('tenant_whatsapp_integrations_phone_number_id_key'), 'tenant_whatsapp_integrations', ['phone_number_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_whatsapp_waba_id'), 'tenant_whatsapp_integrations', ['waba_id'], unique=False)
    op.create_index(op.f('idx_whatsapp_tenant_id'), 'tenant_whatsapp_integrations', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_whatsapp_phone_id'), 'tenant_whatsapp_integrations', ['phone_number_id'], unique=False)
    op.alter_column('tenant_whatsapp_integrations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_whatsapp_integrations', 'connected_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_whatsapp_integrations', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('tenant_whatsapp_integrations', 'access_token_encrypted',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tenant_whatsapp_integrations', 'phone_number_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tenant_whatsapp_integrations', 'waba_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tenant_whatsapp_integrations', 'business_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tenant_whatsapp_integrations', 'provider',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'meta'::text"))
    op.alter_column('system_settings', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_settings', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('system_settings', 'value',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('system_settings', 'key',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('products', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('inventory_movements', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_business_metric_events_tenant_id'), table_name='business_metric_events')
    op.drop_index(op.f('ix_business_metric_events_event_type'), table_name='business_metric_events')
    op.drop_index(op.f('ix_business_metric_events_created_at'), table_name='business_metric_events')
    op.drop_table('business_metric_events')
    op.drop_index(op.f('ix_platform_alerts_type'), table_name='platform_alerts')
    op.drop_index(op.f('ix_platform_alerts_tenant_id'), table_name='platform_alerts')
    op.drop_index(op.f('ix_platform_alerts_severity'), table_name='platform_alerts')
    op.drop_index(op.f('ix_platform_alerts_is_active'), table_name='platform_alerts')
    op.drop_index(op.f('ix_platform_alerts_created_at'), table_name='platform_alerts')
    op.drop_table('platform_alerts')
    op.drop_index(op.f('ix_audit_logs_performed_by'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
