"""checkpoint2_queue_and_metrics

Revision ID: b4adb55e6167
Revises: v1_initial_plural_schema
Create Date: 2026-04-05 23:38:17.686720

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b4adb55e6167"
down_revision: Union[str, None] = "v1_initial_plural_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_customers_phone_number"), table_name="customers")
    op.create_index(
        op.f("ix_customers_phone_number"), "customers", ["phone_number"], unique=False
    )
    op.create_unique_constraint(
        "uq_customer_tenant_phone", "customers", ["tenant_id", "phone_number"]
    )
    op.alter_column(
        "inbound_events",
        "source",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
        existing_server_default=sa.text("'whatsapp'::text"),
    )
    op.alter_column(
        "inbound_events",
        "event_type",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
        existing_server_default=sa.text("'message'::text"),
    )
    op.alter_column(
        "inbound_events",
        "message_sid",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "inbound_events",
        "payload_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "inbound_events",
        "status",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::text"),
    )
    op.alter_column(
        "inbound_events",
        "available_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "inbound_events",
        "locked_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "inbound_events",
        "locked_by",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "inbound_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "inbound_events",
        "processed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "inbound_events",
        "last_error",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_inbound_events_message_sid"), table_name="inbound_events")
    op.drop_index(
        op.f("idx_inbound_events_processing"),
        table_name="inbound_events",
        postgresql_where="(status = 'pending'::text)",
    )
    op.drop_index(op.f("idx_inbound_events_tenant_id"), table_name="inbound_events")
    op.create_index(
        op.f("ix_inbound_events_available_at"),
        "inbound_events",
        ["available_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inbound_events_message_sid"),
        "inbound_events",
        ["message_sid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inbound_events_source"), "inbound_events", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_inbound_events_status"), "inbound_events", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_inbound_events_tenant_id"),
        "inbound_events",
        ["tenant_id"],
        unique=False,
    )
    op.alter_column(
        "metric_snapshots",
        "metric_name",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "metric_snapshots",
        "period_start",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "metric_snapshots",
        "period_end",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "metric_snapshots",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_metric_snapshots_lookup"), table_name="metric_snapshots")
    op.create_index(
        op.f("ix_metric_snapshots_metric_name"),
        "metric_snapshots",
        ["metric_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_snapshots_tenant_id"),
        "metric_snapshots",
        ["tenant_id"],
        unique=False,
    )
    op.alter_column("users", "full_name", existing_type=sa.VARCHAR(), nullable=True)
    op.add_column(
        "whatsapp_configs",
        sa.Column(
            "meta_phone_number_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "whatsapp_configs",
        sa.Column("meta_token_expires_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "whatsapp_configs",
        sa.Column(
            "meta_onboarding_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.add_column(
        "whatsapp_configs", sa.Column("setup_completed", sa.Boolean(), nullable=False)
    )
    op.create_index(
        op.f("ix_whatsapp_configs_meta_onboarding_status"),
        "whatsapp_configs",
        ["meta_onboarding_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_whatsapp_configs_meta_phone_number_id"),
        "whatsapp_configs",
        ["meta_phone_number_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_whatsapp_configs_waba_id"),
        "whatsapp_configs",
        ["waba_id"],
        unique=False,
    )
    op.drop_column("whatsapp_configs", "phone_number_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "whatsapp_configs",
        sa.Column("phone_number_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_whatsapp_configs_waba_id"), table_name="whatsapp_configs")
    op.drop_index(
        op.f("ix_whatsapp_configs_meta_phone_number_id"), table_name="whatsapp_configs"
    )
    op.drop_index(
        op.f("ix_whatsapp_configs_meta_onboarding_status"),
        table_name="whatsapp_configs",
    )
    op.drop_column("whatsapp_configs", "setup_completed")
    op.drop_column("whatsapp_configs", "meta_onboarding_status")
    op.drop_column("whatsapp_configs", "meta_token_expires_at")
    op.drop_column("whatsapp_configs", "meta_phone_number_id")
    op.alter_column("users", "full_name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_index(op.f("ix_metric_snapshots_tenant_id"), table_name="metric_snapshots")
    op.drop_index(
        op.f("ix_metric_snapshots_metric_name"), table_name="metric_snapshots"
    )
    op.create_index(
        op.f("idx_metric_snapshots_lookup"),
        "metric_snapshots",
        ["metric_name", "created_at"],
        unique=False,
    )
    op.alter_column(
        "metric_snapshots",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "metric_snapshots",
        "period_end",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "metric_snapshots",
        "period_start",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "metric_snapshots",
        "metric_name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_inbound_events_tenant_id"), table_name="inbound_events")
    op.drop_index(op.f("ix_inbound_events_status"), table_name="inbound_events")
    op.drop_index(op.f("ix_inbound_events_source"), table_name="inbound_events")
    op.drop_index(op.f("ix_inbound_events_message_sid"), table_name="inbound_events")
    op.drop_index(op.f("ix_inbound_events_available_at"), table_name="inbound_events")
    op.create_index(
        op.f("idx_inbound_events_tenant_id"),
        "inbound_events",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_inbound_events_processing"),
        "inbound_events",
        ["status", "available_at"],
        unique=False,
        postgresql_where="(status = 'pending'::text)",
    )
    op.create_index(
        op.f("idx_inbound_events_message_sid"),
        "inbound_events",
        ["message_sid"],
        unique=False,
    )
    op.alter_column(
        "inbound_events",
        "last_error",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "inbound_events",
        "processed_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "inbound_events",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "inbound_events",
        "locked_by",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "inbound_events",
        "locked_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "inbound_events",
        "available_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "inbound_events",
        "status",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::text"),
    )
    op.alter_column(
        "inbound_events",
        "payload_json",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "inbound_events",
        "message_sid",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "inbound_events",
        "event_type",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'message'::text"),
    )
    op.alter_column(
        "inbound_events",
        "source",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'whatsapp'::text"),
    )
    op.drop_constraint("uq_customer_tenant_phone", "customers", type_="unique")
    op.drop_index(op.f("ix_customers_phone_number"), table_name="customers")
    op.create_index(
        op.f("ix_customers_phone_number"), "customers", ["phone_number"], unique=True
    )
    # ### end Alembic commands ###
