"""add_onboarding_v2_3_state

Revision ID: bdb22424235f
Revises: d24caa5bc67f
Create Date: 2026-04-13 07:31:16.103734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = 'bdb22424235f'
down_revision: Union[str, None] = 'd24caa5bc67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_users', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tenant_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('tenants', sa.Column('onboarding_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='created'))
    op.add_column('tenants', sa.Column('onboarding_step', sa.Integer(), nullable=False, server_default='1'))
    op.execute("UPDATE tenants SET plan_code = 'basic_monthly' WHERE plan_code IS NULL")
    op.alter_column('tenants', 'plan_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_tenants_billing_status'), 'tenants', ['billing_status'], unique=False)
    op.create_index(op.f('ix_tenants_onboarding_state'), 'tenants', ['onboarding_state'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_tenants_onboarding_state'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_billing_status'), table_name='tenants')
    op.alter_column('tenants', 'plan_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tenants', 'onboarding_step')
    op.drop_column('tenants', 'onboarding_state')
    op.alter_column('tenant_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tenant_users', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
