"""phase5_stripe_billing_automation

Revision ID: d24caa5bc67f
Revises: 805150294c2d
Create Date: 2026-04-11 14:43:57.388414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added

# revision identifiers, used by Alembic.
revision: str = "d24caa5bc67f"
down_revision: Union[str, None] = "805150294c2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stripe_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "stripe_event_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.Column("payload", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stripe_events_event_type"),
        "stripe_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stripe_events_stripe_event_id"),
        "stripe_events",
        ["stripe_event_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_stripe_events_tenant_id"), "stripe_events", ["tenant_id"], unique=False
    )
    op.add_column(
        "tenants",
        sa.Column("plan_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "tenants",
        sa.Column(
            "stripe_customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "tenants",
        sa.Column(
            "stripe_subscription_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "tenants",
        sa.Column("stripe_price_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "tenants",
        sa.Column(
            "last_payment_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "tenants",
        sa.Column(
            "last_stripe_event_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_tenants_plan_code"), "tenants", ["plan_code"], unique=False
    )
    op.create_index(
        op.f("ix_tenants_stripe_customer_id"),
        "tenants",
        ["stripe_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tenants_stripe_subscription_id"),
        "tenants",
        ["stripe_subscription_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenants_stripe_subscription_id"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_stripe_customer_id"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_plan_code"), table_name="tenants")
    op.drop_column("tenants", "last_stripe_event_id")
    op.drop_column("tenants", "last_payment_status")
    op.drop_column("tenants", "stripe_price_id")
    op.drop_column("tenants", "stripe_subscription_id")
    op.drop_column("tenants", "stripe_customer_id")
    op.drop_column("tenants", "plan_code")
    op.drop_index(op.f("ix_stripe_events_tenant_id"), table_name="stripe_events")
    op.drop_index(op.f("ix_stripe_events_stripe_event_id"), table_name="stripe_events")
    op.drop_index(op.f("ix_stripe_events_event_type"), table_name="stripe_events")
    op.drop_table("stripe_events")
    # ### end Alembic commands ###
